version: '2'

services:
  web-devel: 
    image: ruby:3.3.0
    ports: 
      - "3000:3000"
    volumes:
      - ${PWD}:/usr/src/app/
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: root
