# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_wmaino_dev
  username: postgres
  password: 8763ggtAhh
  host: localhost

test:
  <<: *default
  database: blog_wmaino_test
  username: postgres
  password: 8763ggtAhh
  host: localhost

production:
  <<: *default
  database: blog_wmaino_production
  username: postgres
  password: <%= ENV["DB_8763ggtAhh"] %>
  host: localhost
